# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogvs < Formula
  desc "Go implementation of SVGO — the SVG optimizer"
  homepage "https://github.com/okooo5km/ogvs"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.0/ogvs_0.1.0_darwin_amd64.tar.gz"
      sha256 "af22d61c86c03708f1731a2730a4d671cc32aa5b5dcd09574eb588b6eddde731"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.0/ogvs_0.1.0_darwin_arm64.tar.gz"
      sha256 "e4f3943ec8c64ba175963f36adac4df9ef0f4d4fddb029b91cfb10ba425b8666"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.0/ogvs_0.1.0_linux_amd64.tar.gz"
      sha256 "103fb37d70215c12b42186476492958b0d2dcbf7655b7020e9af80a77097254d"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.0/ogvs_0.1.0_linux_arm64.tar.gz"
      sha256 "e562be627c781ca897ba1985c58d3d689ca46470740347739944ef9df27c7539"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  test do
    system bin/"ogvs", "--version"
  end
end
