# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogvs < Formula
  desc "Go implementation of SVGO — the SVG optimizer"
  homepage "https://github.com/okooo5km/ogvs"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.2/ogvs_0.1.2_darwin_amd64.tar.gz"
      sha256 "4adbbc379237f12507deb2049fb7a87ddf37d22e4978e3be054c9e2bd5735860"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.2/ogvs_0.1.2_darwin_arm64.tar.gz"
      sha256 "6b2730016259f44b2c0108dfec0b4759db6712c6602b0f634fe644613239db3f"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.2/ogvs_0.1.2_linux_amd64.tar.gz"
      sha256 "852db2c221bce80966b4ccb20b5b81853fa472ef5ad646273c569a853fa0d7db"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.2/ogvs_0.1.2_linux_arm64.tar.gz"
      sha256 "5449ab2e3f22f0e8fb6141eb64a389af3d281f1d98e0c7d9e50b866b29412fd8"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  test do
    system bin/"ogvs", "--version"
  end
end
