# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Coupongo < Formula
  desc "AI-friendly CLI for managing Stripe coupons and promotion codes"
  homepage "https://github.com/okooo5km/coupongo"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/coupongo/releases/download/v0.2.0/coupongo_0.2.0_darwin_amd64.tar.gz"
      sha256 "96dfd5ae2725aeecc77dcad3d09209c26ed8d5f9d49468f4c546fcbee60fae7e"

      define_method(:install) do
        bin.install "coupongo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/coupongo/releases/download/v0.2.0/coupongo_0.2.0_darwin_arm64.tar.gz"
      sha256 "78a83edc9094d74639aea98d1bb2a838f8c09ef50381fb799edccaca55ae8da6"

      define_method(:install) do
        bin.install "coupongo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/coupongo/releases/download/v0.2.0/coupongo_0.2.0_linux_amd64.tar.gz"
      sha256 "a6ee31fde6e7a5667ae87aad761e8865eea30d0f771912433259b738ff51771a"
      define_method(:install) do
        bin.install "coupongo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/coupongo/releases/download/v0.2.0/coupongo_0.2.0_linux_arm64.tar.gz"
      sha256 "72dbfc9df7a3f4c639e539e60865bc24bcce9af02d7d4fabc0ac8a2387df5608"
      define_method(:install) do
        bin.install "coupongo"
      end
    end
  end

  test do
    system "#{bin}/coupongo", "version"
  end
end
