# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mms < Formula
  desc "A high-performance Go implementation of a knowledge graph memory server for MCP"
  homepage "https://github.com/okooo5km/memory-mcp-server-go"
  version "0.5.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.5.0/mms_0.5.0_darwin_amd64.tar.gz"
      sha256 "f3fed3f0966ec84e0e3048c7cf99cc7e772a516c7b122afe23818f4819c165c9"

      define_method(:install) do
        bin.install "mms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.5.0/mms_0.5.0_darwin_arm64.tar.gz"
      sha256 "ffed6f23a00c8ee30f5bb0d9066b497b40f7bf0d1d7df1f620c2ac45b0885443"

      define_method(:install) do
        bin.install "mms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.5.0/mms_0.5.0_linux_amd64.tar.gz"
      sha256 "15c84df8e9a6b802623eab58741e0dbac18e470eee0db037a74c9bb9c8626601"
      define_method(:install) do
        bin.install "mms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.5.0/mms_0.5.0_linux_arm64.tar.gz"
      sha256 "55c026c45b7e02b4c89a02544f12d46324d762c7a69685c7b2038a33455dc537"
      define_method(:install) do
        bin.install "mms"
      end
    end
  end

  test do
    system "#{bin}/mms", "--version"
  end
end
