# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mms < Formula
  desc "A high-performance Go implementation of a knowledge graph memory server for MCP"
  homepage "https://github.com/okooo5km/memory-mcp-server-go"
  version "0.3.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.3.2/mms_0.3.2_darwin_amd64.tar.gz"
      sha256 "d59629fb50699a855ede07437904decc6f4ae7e8ca62f592dffb8f5cfdfb035f"

      define_method(:install) do
        bin.install "mms"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.3.2/mms_0.3.2_darwin_arm64.tar.gz"
      sha256 "82cdb9fe5c4ccf1caa3b51df8391e8a38a2777e560bd865156f359656fa3b049"

      define_method(:install) do
        bin.install "mms"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.3.2/mms_0.3.2_linux_amd64.tar.gz"
      sha256 "cf5a383f986b79171ea13f6d9586b6341466952123d7217bfafae873d45f0689"
      define_method(:install) do
        bin.install "mms"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/memory-mcp-server-go/releases/download/v0.3.2/mms_0.3.2_linux_arm64.tar.gz"
      sha256 "ddf8653cfe03f405e915a615db1f6f2349898c40fa7e692015e326969d4edbf5"
      define_method(:install) do
        bin.install "mms"
      end
    end
  end

  test do
    system "#{bin}/mms", "--version"
  end
end
