# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogvs < Formula
  desc "Go implementation of SVGO — the SVG optimizer"
  homepage "https://github.com/okooo5km/ogvs"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.2.0/ogvs_0.2.0_darwin_amd64.tar.gz"
      sha256 "8af346af7eee4e52f67a3dfe5301053294a562405eb40c42ed1ca7cb8a158018"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.2.0/ogvs_0.2.0_darwin_arm64.tar.gz"
      sha256 "8fe5b7cce47123586c0dc21225e23edf2d99499859c23cd3c1afa30e8e8f14f5"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.2.0/ogvs_0.2.0_linux_amd64.tar.gz"
      sha256 "afe9a14b5204229ceae957953b684874974e436f2fa77c35e1381e8a2095d2fc"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.2.0/ogvs_0.2.0_linux_arm64.tar.gz"
      sha256 "88dae11a7b895e7330bac94414e23d8836a101a9faf685bfcf68c0a9f1cb5d51"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  test do
    system bin/"ogvs", "--version"
  end
end
