# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ogvs < Formula
  desc "Go implementation of SVGO — the SVG optimizer"
  homepage "https://github.com/okooo5km/ogvs"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.3/ogvs_0.1.3_darwin_amd64.tar.gz"
      sha256 "e27e4d0a5389294d643ea90652ec6918350e320ee54e07867b83ed436950fcc7"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.3/ogvs_0.1.3_darwin_arm64.tar.gz"
      sha256 "433c532679cf54b8b15a5f9c25100b770665b8ea9939b2feca01b3e4e5d83f40"

      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.3/ogvs_0.1.3_linux_amd64.tar.gz"
      sha256 "11f51533569c26a89b80608b61ed40b2c70a059eaec6ec142ad901cacde07bde"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/okooo5km/ogvs/releases/download/v0.1.3/ogvs_0.1.3_linux_arm64.tar.gz"
      sha256 "0ea5fd6ac323e7a0c169c92e1423003a86b55745fc729a1a56349820dba4ea22"
      define_method(:install) do
        bin.install "ogvs"
      end
    end
  end

  test do
    system bin/"ogvs", "--version"
  end
end
